apiVersion: v1
kind: ServiceAccount
metadata:
  name: lumos-admin
  namespace: lumos-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lumos-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # Full unrestricted access
subjects:
  - kind: ServiceAccount
    name: lumos-admin
    namespace: lumos-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumos
  namespace: lumos-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lumos
  template:
    metadata:
      labels:
        app: lumos
    spec:
      serviceAccountName: lumos-admin
      containers:
        - name: lumos
          image: lumos
          ports:
            - containerPort: 8080
          env:
            - name: LEVEL
              value: DEBUG
            - name: MQTT_BROKER
              value: mqtt://mosquitto.mosquitto.svc.cluster.local:1883
---
apiVersion: v1
kind: Service
metadata:
  name: lumos
  namespace: lumos-dev
spec:
  selector:
    app: lumos
  ports:
    - port: 80
      targetPort: 8080
